export const REGISTER_WAITING = 'REGISTER_WAITING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SERVER_ERROR = 'REGISTER_SERVER_ERROR';

export const LOGIN_WAITING = 'LOGIN_WAITING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_PROBLEM_LIST_WAITING = 'GET_PROBLEM_LIST_WAITING';
export const GET_PROBLEM_LIST_SUCCESS = 'GET_PROBLEM_LIST_SUCCESS';
export const GET_PROBLEM_LIST_FAIL = 'GET_PROBLEM_LIST_FAIL';
